name: Blob Build

on:
  push:
    branches:
      - master
      - experimental

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Upload to Blob Builds (Dev)
        uses: WalshyDev/blob-builds/gh-action@main
        if: github.ref == 'refs/heads/master'
        with:
          project: GeneticChickengineering-Reborn
          releaseChannel: Dev
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}

      - name: Upload to Blob Builds (Experimetal)
        uses: WalshyDev/blob-builds/gh-action@main
        if: github.ref == 'refs/heads/experimental'
        with:
          project: GeneticChickengineering-Reborn
          releaseChannel: Experimental
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
